name: Show current master in step summary

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  emitCommit:
    runs-on: ubuntu-latest
    steps:
    - name: Pre-checkout hash
      run: echo "### SHA of master is: $GITHUB_SHA" >> $GITHUB_STEP_SUMMARY
    - uses: actions/checkout@main
    - name: Post-checkout sha
      run: echo "### SHA of master is: $GITHUB_SHA" >> $GITHUB_STEP_SUMMARY
