name: Show current master in step summary

on:
  schedule:
    - cron: '0,4,8,12,16,20,24,28,32,36,40,44,48,52,55,59 * * * *'

jobs:
  emitCommit:
    runs-on: ubuntu-latest

    steps:
      - name: Pre-checkout hash
        shell: bash
        run: echo "SHA of master is:" $GITHUB_SHA >> $GITHUB_STEP_SUMMARY
      - uses: actions/checkout@v6
      - name: Post-checkout sha
        shell: bash
        run: echo "SHA of master is:" $GITHUB_SHA >> $GITHUB_STEP_SUMMARY
